version: 2
updates:
  - package-ecosystem: npm
    directory: '/packages/xchain-utxo'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-evm'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-cosmos-sdk'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-client'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-aggregator'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-arbitrum'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-avax'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-base'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-bsc'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-cardano'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-cosmos'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    directory: '/packages/xchain-dash'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
