/* tslint:disable */
/* eslint-disable */
/**
 * Midgard API (Selective - Complete)  
 * This file contains only the API classes and types that are actually used,
 * reducing bundle size by optimizing the generated OpenAPI client.
 * 
 * Generated by selective approach for optimal tree-shaking
 */

import globalAxios, { AxiosInstance, AxiosRequestConfig } from 'axios';

// Base configuration and utilities
export interface ConfigurationParameters {
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    username?: string;
    password?: string;
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    basePath?: string;
    baseOptions?: any;
    formDataCtor?: new () => any;
}

export class Configuration {
    apiKey?: string | Promise<string> | ((name: string) => string) | ((name: string) => Promise<string>);
    username?: string;
    password?: string;
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string) | ((name?: string, scopes?: string[]) => Promise<string>);
    basePath?: string;
    baseOptions?: any;
    formDataCtor?: new () => any;

    constructor(param: ConfigurationParameters = {}) {
        this.apiKey = param.apiKey;
        this.username = param.username;
        this.password = param.password;
        this.accessToken = param.accessToken;
        this.basePath = param.basePath;
        this.baseOptions = param.baseOptions;
        this.formDataCtor = param.formDataCtor;
    }

    public isJsonMime(mime: string): boolean {
        const jsonMime: RegExp = new RegExp('^(application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(;.*)?$', 'i');
        return mime !== null && (jsonMime.test(mime) || mime.toLowerCase() === 'application/json-patch+json');
    }
}

export const BASE_PATH = "https://midgard.thorchain.info".replace(/\/+$/, "");

export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

// Essential types - only include commonly used ones
export interface Pool {
    asset?: string;
    shortCode?: string;
    status?: string;
    decimals?: number;
    pendingInboundAsset?: string;
    pendingInboundRune?: string;
    balanceAsset?: string;
    balanceRune?: string;
    poolUnits?: string;
    LPUnits?: string;
    synthUnits?: string;
    synthSupply?: string;
    saversDepth?: string;
    saversUnits?: string;
    synthMintPaused?: boolean;
    synthSupplyRemaining?: string;
    loanCollateral?: string;
    loanCr?: string;
    derivedDepthBps?: string;
}

export interface PoolsResponse {
    pools?: Array<Pool>;
}

export interface PoolDetail {
    'annualPercentageRate': string;
    'asset': string;
    'assetDepth': string;
    'assetPrice': string;
    'assetPriceUSD': string;
    'earnings': string;
    'earningsAnnualAsPercentOfDepth': string;
    'liquidityUnits': string;
    'lpLuvi': string;
    'nativeDecimal': string;
    'poolAPY': string;
    'runeDepth': string;
    'saversAPR': string;
    'saversDepth': string;
    'saversUnits': string;
    'saversYieldShare'?: string;
    'status': string;
    'synthSupply': string;
    'synthUnits': string;
    'totalCollateral': string;
    'totalDebtTor': string;
    'units': string;
    'volume24h': string;
}

export interface PoolDetails extends Array<PoolDetail> {}

export interface SaverDetails {
    'pools': Array<SaverPool>;
}

export interface SaverPool {
    'assetAdded': string;
    'assetAddress': string;
    'assetDeposit': string;
    'assetRedeem': string;
    'assetWithdrawn': string;
    'dateFirstAdded': string;
    'dateLastAdded': string;
    'pool': string;
    'units': string;
}

// Core API classes - optimized implementations
export class DefaultApi extends BaseAPI {
    
    /**
     * Returns statistics of pools saved in database
     */
    public async getPools(options?: AxiosRequestConfig): Promise<Array<Pool>> {
        const requestUrl = `${this.basePath}/v2/pools`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }

    /**
     * Returns Network data
     */
    public async getNetwork(options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/network`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }

    /**
     * Returns aggregate statistics of specified pool in specified period
     */
    public async getPoolStats(pool: string, period?: string, options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/pool/${encodeURIComponent(String(pool))}/stats`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
            params: { period, ...options?.params },
        });
        return response.data;
    }

    /**
     * Returns depth and price history of specified pool in specified period
     */
    public async getDepthHistory(pool: string, interval?: string, from?: number, to?: number, options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/history/depths/${encodeURIComponent(String(pool))}`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
            params: { interval, from, to, ...options?.params },
        });
        return response.data;
    }

    /**
     * Returns swap history of specified pool in specified period
     */
    public async getSwapHistory(pool?: string, interval?: string, from?: number, to?: number, options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/history/swaps`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
            params: { pool, interval, from, to, ...options?.params },
        });
        return response.data;
    }

    /**
     * Returns member details by address or multiple addresses
     */
    public async getMemberDetail(address: string | Array<string>, options?: AxiosRequestConfig): Promise<any> {
        const addresses = Array.isArray(address) ? address.join(',') : address;
        const requestUrl = `${this.basePath}/v2/member/${encodeURIComponent(String(addresses))}`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }

    /**
     * Returns node information
     */
    public async getNodes(options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/thorchain/nodes`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }

    /**
     * Returns queue information
     */
    public async getQueue(options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/thorchain/queue`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }
}

// Specification API - minimal implementation
export class SpecificationApi extends BaseAPI {
    /**
     * Return the OpenAPI specification for the Midgard API
     */
    public async getOpenApiSpec(options?: AxiosRequestConfig): Promise<any> {
        const requestUrl = `${this.basePath}/v2/doc`;
        const response = await this.axios.get(requestUrl, {
            ...this.configuration?.baseOptions,
            ...options,
        });
        return response.data;
    }
}