name: Release workflow

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn increase-packages
          publish: yarn publish-packages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prepare notification for Discord
        id: prepare-notification
        if: steps.changesets.outputs.published == 'true'
        run: yarn notification:prepare ${{ toJSON(steps.changesets.outputs.publishedPackages) }}

      - name: Send discord notification
        if: steps.prepare-notification.outputs.success == 'true'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ steps.prepare-notification.outputs.embeds }}
        uses: Ilshidur/action-discord@0.3.2
